spring:
  application:
    name: post-service
  profiles:
    active: prod
  config:
    import: "optional:configserver:http://nyamnyam-config-server-0fcb3-100204825-630f1c851357.kr.lb.naverncp.com:8888/"
