server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
spring:
  profiles:
    active: prod
  config:
    import: "optional:configserver:http://nyamnyam-config-server-0fcb3-100204825-630f1c851357.kr.lb.naverncp.com:8888/"
