spring:
  application:
    name: gateway-server
  profiles:
    active: local
  config:
    import: optional:configserver:http://localhost:8888


jwt:
  secret: "bywm4zC5-vR36j_mZPsd4jmNFUuny0XuYoln59AStsI="
  expiration: 3600000  # 1시간 (초단위)