spring:
  application:
    name: admin
  datasource:
    url: jdbc:mysql://localhost:3306/nyamnyamdb
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 20MB
      max-request-size: 20MB

  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: e2iaB9q3A_kk1k7hX6Qi
            client-secret: Av6eAE_PsV
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/api/user/login/oauth2/code/naver
            client-name: Naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-info-authentication-method: header
            user-name-attribute: response

  profiles:
    active: local
  config:
    import: optional:configserver:http://localhost:8888

naver:
  storage:
    accessKey: ncp_iam_BPASKR4hDZEqhZxoJTU0
    secretKey: ncp_iam_BPKSKRW7EiCKxGGi0L9AODsJCwtJ8wcZ9a
    bucket: nyamnyam.storage
    upload:
      path: uploads/posts
  service:
    url: https://7nwpqtihrd.apigw.ntruss.com/custom/v1/34395/aa4546960f3df79d2062eefa7579aa0d04c878e42fdc0eb7754bcbb8f2e008bf/general
    secretKey: Q1laWml3WFdMaWprT2JxQ3ZxTkR4ZEJOQnhoc3huYXM=